# Generated by Django 5.1.4 on 2024-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(related_name='games', to='task1.buyer'),
        ),
    ]
