# Generated by Django 5.1.4 on 2024-12-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='INNList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inn', models.CharField(max_length=16)),
                ('user', models.ManyToManyField(related_name='inns', to='monitoring.user')),
            ],
        ),
    ]
