# Generated by Django 5.1.4 on 2024-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innlist',
            name='pdffile',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
