# Generated by Django 5.1.4 on 2024-12-13 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_alter_buyer_age_alter_buyer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(14)]),
        ),
    ]
